const SPACES = [
    {id: '0',       coord: (0,0),    value: 'start',  next: ('1')}, 
    {id: '1',       coord: (0,0),    value: 'bat',    next: ('2')},
    {id: '2',       coord: (0,0),    value: 'dagger', next: ('3')},
    {id: '3',       coord: (0,0),    value: 'goblet', next: ('4')},
    {id: '4',       coord: (0,0),    value: 'spider', next: ('5')},
    {id: '5',       coord: (0,0),    value: 'double', next: ('6')},
    {id: '6',       coord: (0,0),    value: 'double', next: ('7', '6a')},
        {id: '6a',       coord: (0,0),    value: 'b', next: ('6b')},
        {id: '6b',       coord: (0,0),    value: 'vb', next: ('6c')},
        {id: '6c',       coord: (0,0),    value: 'vb', next: ('19')},
    {id: '7',       coord: (0,0),    value: 'double', next: ('8')},
    {id: '8',       coord: (0,0),    value: 'double', next: ('9')},
    {id: '9',       coord: (0,0),    value: 'double', next: ('10')},
    {id: '10',      coord: (0,0),    value: 'bat',    next: ('11')},
    {id: '11',      coord: (0,0),    value: 'dagger', next: ('12', '11a')},
        {id: '11a',      coord: (0,0),    value: 'dagger', next: ('11b')},
        {id: '11b',      coord: (0,0),    value: 'dagger', next: ('17')},
    {id: '12',      coord: (0,0),    value: 'single', next: ('13')},
    {id: '13',      coord: (0,0),    value: 'black', next: ('14')},
    {id: '14',      coord: (0,0),    value: 'goblet', next: ('15')},
    {id: '15',      coord: (0,0),    value: 'spider', next: ('16')},
    {id: '16',      coord: (0,0),    value: 'double', next: ('17')},
    {id: '17',      coord: (0,0),    value: 'double', next: ('18')},
    {id: '18',      coord: (0,0),    value: 'black', next: ('19')},
    {id: '19',      coord: (0,0),    value: 'spider', next: ('20')},
    {id: '20',      coord: (0,0),    value: 'red', next: ('21')},
    {id: '21',      coord: (0,0),    value: 'red', next: ('22')},
    {id: '22',      coord: (0,0),    value: 'single', next: ('23')},
    {id: '23',      coord: (0,0),    value: 'double', next: ('24', '23a')},
        {id: '23a',      coord: (0,0),    value: 'b', next: ('23b')},
        {id: '23b',      coord: (0,0),    value: 'vb', next: ('23c')},
        {id: '23c',      coord: (0,0),    value: 'vb', next: ('33')},
    {id: '24',      coord: (0,0),    value: 'vb', next: ('25')},
    {id: '25',      coord: (0,0),    value: 'black', next: ('26')},
    {id: '26',      coord: (0,0),    value: 'dagger', next: ('27')},
    {id: '27',      coord: (0,0),    value: 'dagger', next: ('28')},
    {id: '28',      coord: (0,0),    value: 'dagger', next: ('29')},
    {id: '29',      coord: (0,0),    value: 'single', next: ('30')},
    {id: '30',      coord: (0,0),    value: 'single', next: ('31')},
    {id: '31',      coord: (0,0),    value: 'single', next: ('32', '31a')},
        {id: '31a',      coord: (0,0),    value: 'b', next: ('31b')},
        {id: '31b',      coord: (0,0),    value: 'vb', next: ('31c')},
        {id: '31c',      coord: (0,0),    value: 'vb', next: ('31d')},
        {id: '31d',      coord: (0,0),    value: 'single', next: ('47')},

    {id: '32',      coord: (0,0),    value: 'black',  next: ('33')},
    {id: '33',      coord: (0,0),    value: 'vb',     next: ('34')},
    {id: '34',      coord: (0,0),    value: 'spider', next: ('35')},
    {id: '35',      coord: (0,0),    value: 'black',  next: ('36')},
    {id: '36',      coord: (0,0),    value: 'bat',    next: ('37')},
    {id: '37',      coord: (0,0),    value: 'double', next: ('38')},
    {id: '38',      coord: (0,0),    value: 'vb',     next: ('39')},
    {id: '39',      coord: (0,0),    value: 'goblet', next: ('40')},
    {id: '40',      coord: (0,0),    value: 'goblet', next: ('41')},
    {id: '41',      coord: (0,0),    value: 'bat',    next: ('42')},
    {id: '42',      coord: (0,0),    value: 'bat',    next: ('43')},
    {id: '43',      coord: (0,0),    value: 'bat',    next: ('44', '43a')},
        {id: '43a',      coord: (0,0),    value: 'b',    next: ('43b')},
        {id: '43b',      coord: (0,0),    value: 'b',    next: ('43c')},
        {id: '43c',      coord: (0,0),    value: 'bat',    next: ('58')},
        {id: '44',      coord: (0,0),    value: 'single', next: ('45')},

    {id: '45',      coord: (0,0),    value: 'double', next: ('46', '45a')},
        {id: '45a',      coord: (0,0),    value: 'b', next: ('45b')},
        {id: '45b',      coord: (0,0),    value: 'vb', next: ('45c')},
        {id: '45c',      coord: (0,0),    value: 'vb', next: ('56')},

    {id: '46',      coord: (0,0),    value: 'red',    next: ('47')},
    {id: '47',      coord: (0,0),    value: 'red',    next: ('48', '47a')},
        {id: '47a',      coord: (0,0),    value: 'goblet',    next: ('47b')},
        {id: '47b',      coord: (0,0),    value: 'goblet',    next: ('47c')},
        {id: '47c',      coord: (0,0),    value: 'goblet',    next: ('54')},

    {id: '48',      coord: (0,0),    value: 'red',    next: ('49')},
    {id: '49',      coord: (0,0),    value: 'black',  next: ('50')},
    {id: '50',      coord: (0,0),    value: 'single', next: ('51')},
    {id: '51',      coord: (0,0),    value: 'double', next: ('52')},
    {id: '52',      coord: (0,0),    value: 'spider', next: ('53')},
    {id: '53',      coord: (0,0),    value: 'goblet', next: ('54')},
    {id: '54',      coord: (0,0),    value: 'red',    next: ('55')},
    {id: '55',      coord: (0,0),    value: 'spider', next: ('56')},
    {id: '56',      coord: (0,0),    value: 'vb',     next: ('57')},
    {id: '57',      coord: (0,0),    value: 'black',  next: ('58')},
    {id: '58',      coord: (0,0),    value: 'bat',    next: ('59')},
    {id: '59',      coord: (0,0),    value: 'black',  next: ('60')},
    {id: '60',      coord: (0,0),    value: 'goblet', next: ('61')},
    {id: '61',      coord: (0,0),    value: 'spider', next: ('62')},
    {id: '62',      coord: (0,0),    value: 'goblet', next: ('63')},
    {id: '63',      coord: (0,0),    value: 'spider', next: ('64', '63a')},
        {id: '63a',      coord: (0,0),    value: 'b', next: ('63b')},
        {id: '63b',      coord: (0,0),    value: 'b', next: ('71')},

    {id: '64',      coord: (0,0),    value: 'black',  next: ('65')},
    {id: '65',      coord: (0,0),    value: 'black',  next: ('66')},
    {id: '66',      coord: (0,0),    value: 'black',  next: ('67')},
    {id: '67',      coord: (0,0),    value: 'dagger', next: ('68')},
    {id: '68',      coord: (0,0),    value: 'goblet', next: ('69')},
    {id: '69',      coord: (0,0),    value: 'vb',     next: ('70')},
    {id: '70',      coord: (0,0),    value: 'red',    next: ('71')},
    {id: '71',      coord: (0,0),    value: 'vb',     next: ('72')},
    {id: '72',      coord: (0,0),    value: 'goblet', next: ('73')},
    {id: '73',      coord: (0,0),    value: 'goblet', next: ('74')},
    {id: '74',      coord: (0,0),    value: 'goblet', next: ('')},
    
]

export {SPACES};